[package]
name = "criterion-plot"
description = "Criterion's plotting library"
categories = ["visualization"]
keywords = ["plotting", "gnuplot", "criterion"]
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
cast = "0.3"
itertools = "0.13"

[dev-dependencies]
itertools-num = "0.1"
num-complex = { version = "0.4", default-features = false, features = ["std"] }
rand = "0.8"

[badges]
maintenance = { status = "looking-for-maintainer" }
